/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import javax.swing.JOptionPane;
import model.Address;
import model.ContactInfo;
import model.Person;

/**
 *
 * @author haoliu
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private Person person;
    private Address address;
    private ContactInfo contactinfo;
    
    public MainJFrame() {
        initComponents();
        
        this.person = new Person();
        this.address = new Address();
        this.contactinfo = new ContactInfo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        UserFormPanel = new javax.swing.JPanel();
        userFirstName = new javax.swing.JLabel();
        userCurrentStreetName = new javax.swing.JLabel();
        fieldFirstName = new javax.swing.JTextField();
        fieldCurrentStreetName = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        userLastName = new javax.swing.JLabel();
        fieldLastName = new javax.swing.JTextField();
        userNUID = new javax.swing.JLabel();
        fieldNUID = new javax.swing.JTextField();
        userCollegeName = new javax.swing.JLabel();
        fieldCollegeName = new javax.swing.JTextField();
        userPhoneNumber = new javax.swing.JLabel();
        fieldPhoneNumber = new javax.swing.JTextField();
        userEmailAddress = new javax.swing.JLabel();
        fieldEmailAddress = new javax.swing.JTextField();
        fieldCurrentAptNumber = new javax.swing.JTextField();
        userCurrentAptNumber = new javax.swing.JLabel();
        fieldCurrentCityName = new javax.swing.JTextField();
        fieldCurrentStateName = new javax.swing.JTextField();
        userCurrentStateName = new javax.swing.JLabel();
        userCurrentCityName = new javax.swing.JLabel();
        fieldCurrentZipCode = new javax.swing.JTextField();
        userCurrentZipCode = new javax.swing.JLabel();
        fieldPermanentStreetName = new javax.swing.JTextField();
        fieldPermanentZipCode = new javax.swing.JTextField();
        userPermanentZipCode = new javax.swing.JLabel();
        fieldPermanentAptNumber = new javax.swing.JTextField();
        userPermanentAptNumber = new javax.swing.JLabel();
        fieldPermanentCityName = new javax.swing.JTextField();
        userPermanentStreetName = new javax.swing.JLabel();
        fieldPermanentStateName = new javax.swing.JTextField();
        userPermanentStateName = new javax.swing.JLabel();
        userPermanentCityName = new javax.swing.JLabel();
        ViewPanel = new javax.swing.JPanel();
        viewNUID = new javax.swing.JLabel();
        viewFirstName = new javax.swing.JLabel();
        viewLastName = new javax.swing.JLabel();
        viewCollegeName = new javax.swing.JLabel();
        viewPhoneNum = new javax.swing.JLabel();
        viewEmailAddress = new javax.swing.JLabel();
        viewCurrentStreetName = new javax.swing.JLabel();
        viewCurrentAptNumber = new javax.swing.JLabel();
        viewCurrentCityName = new javax.swing.JLabel();
        viewCurrentStateName = new javax.swing.JLabel();
        viewCurrentZipCode = new javax.swing.JLabel();
        viewPermanentStreetName = new javax.swing.JLabel();
        viewPermanentAptNumber = new javax.swing.JLabel();
        viewPermanentCityName = new javax.swing.JLabel();
        viewPermanentStateName = new javax.swing.JLabel();
        viewPermanentZipCode = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setBackground(new java.awt.Color(255, 255, 255));

        UserFormPanel.setBackground(new java.awt.Color(204, 204, 255));

        userFirstName.setText("FirstName:");

        userCurrentStreetName.setText("CurrentStreetName:");

        fieldFirstName.setText("Hao");

        fieldCurrentStreetName.setText("34 Munroe St");
        fieldCurrentStreetName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCurrentStreetNameActionPerformed(evt);
            }
        });

        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        userLastName.setText("LastName:");

        fieldLastName.setText("Liu");

        userNUID.setText("NUID:");

        fieldNUID.setText("001202400");
        fieldNUID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNUIDActionPerformed(evt);
            }
        });

        userCollegeName.setText("CollegeName:");

        fieldCollegeName.setText("COE");
        fieldCollegeName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCollegeNameActionPerformed(evt);
            }
        });

        userPhoneNumber.setText("PhoneNum:");

        fieldPhoneNumber.setText("8573038087");
        fieldPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPhoneNumberActionPerformed(evt);
            }
        });

        userEmailAddress.setText("EmailAddress:");

        fieldEmailAddress.setText("liu.hao5@northeastern.edu");
        fieldEmailAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldEmailAddressActionPerformed(evt);
            }
        });

        fieldCurrentAptNumber.setText("Apt 801");
        fieldCurrentAptNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCurrentAptNumberActionPerformed(evt);
            }
        });

        userCurrentAptNumber.setText("CurrentAptNumber:");

        fieldCurrentCityName.setText("Lynn");
        fieldCurrentCityName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCurrentCityNameActionPerformed(evt);
            }
        });

        fieldCurrentStateName.setText("MA");
        fieldCurrentStateName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCurrentStateNameActionPerformed(evt);
            }
        });

        userCurrentStateName.setText("CurrentStateName:");

        userCurrentCityName.setText("CurrentCityName:");

        fieldCurrentZipCode.setText("01901");
        fieldCurrentZipCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCurrentZipCodeActionPerformed(evt);
            }
        });

        userCurrentZipCode.setText("CurrentZipCode:");

        fieldPermanentStreetName.setText("No.528 North Guangxi Rd");
        fieldPermanentStreetName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPermanentStreetNameActionPerformed(evt);
            }
        });

        fieldPermanentZipCode.setText("200001");
        fieldPermanentZipCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPermanentZipCodeActionPerformed(evt);
            }
        });

        userPermanentZipCode.setText("PermanentZipCode:");

        fieldPermanentAptNumber.setText("Rm 1607");
        fieldPermanentAptNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPermanentAptNumberActionPerformed(evt);
            }
        });

        userPermanentAptNumber.setText("PermanentAptNumber:");

        fieldPermanentCityName.setText("Shanghai");
        fieldPermanentCityName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPermanentCityNameActionPerformed(evt);
            }
        });

        userPermanentStreetName.setText("PermanentStreetName:");

        fieldPermanentStateName.setText("Shanghai");
        fieldPermanentStateName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPermanentStateNameActionPerformed(evt);
            }
        });

        userPermanentStateName.setText("PermanentStateName:");

        userPermanentCityName.setText("PermanentCityName:");

        javax.swing.GroupLayout UserFormPanelLayout = new javax.swing.GroupLayout(UserFormPanel);
        UserFormPanel.setLayout(UserFormPanelLayout);
        UserFormPanelLayout.setHorizontalGroup(
            UserFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserFormPanelLayout.createSequentialGroup()
                .addGroup(UserFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UserFormPanelLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(UserFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(UserFormPanelLayout.createSequentialGroup()
                                .addGroup(UserFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(userFirstName)
                                    .addComponent(userNUID))
                                .addGap(89, 89, 89)
                                .addGroup(UserFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldFirstName)
                                    .addComponent(fieldNUID)))
                            .addGroup(UserFormPanelLayout.createSequentialGroup()
                                .addGroup(UserFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(userCollegeName)
                                    .addComponent(userLastName)
                                    .addComponent(userPhoneNumber)
                                    .addComponent(userEmailAddress)
                                    .addComponent(userCurrentStreetName)
                                    .addComponent(userCurrentAptNumber)
                                    .addComponent(userCurrentCityName)
                                    .addComponent(userCurrentStateName))
                                .addGap(34, 34, 34)
                                .addGroup(UserFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldCurrentZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(UserFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(fieldLastName)
                                        .addComponent(fieldCollegeName)
                                        .addComponent(fieldPhoneNumber)
                                        .addComponent(fieldEmailAddress)
                                        .addComponent(fieldCurrentStreetName)
                                        .addComponent(fieldCurrentAptNumber)
                                        .addComponent(fieldCurrentCityName)
                                        .addComponent(fieldCurrentStateName, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(UserFormPanelLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(UserFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(UserFormPanelLayout.createSequentialGroup()
                                .addComponent(userPermanentZipCode)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fieldPermanentZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(UserFormPanelLayout.createSequentialGroup()
                                .addComponent(userPermanentStateName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fieldPermanentStateName, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(UserFormPanelLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(UserFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(UserFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(UserFormPanelLayout.createSequentialGroup()
                                            .addComponent(userPermanentAptNumber)
                                            .addGap(18, 18, 18)
                                            .addComponent(fieldPermanentAptNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(UserFormPanelLayout.createSequentialGroup()
                                            .addComponent(userPermanentStreetName)
                                            .addGap(18, 18, 18)
                                            .addComponent(fieldPermanentStreetName, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(userCurrentZipCode))
                                    .addGroup(UserFormPanelLayout.createSequentialGroup()
                                        .addComponent(userPermanentCityName)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(fieldPermanentCityName, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(UserFormPanelLayout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(save)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        UserFormPanelLayout.setVerticalGroup(
            UserFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UserFormPanelLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(UserFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userNUID)
                    .addComponent(fieldNUID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UserFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userFirstName)
                    .addComponent(fieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UserFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userLastName)
                    .addComponent(fieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UserFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userCollegeName)
                    .addComponent(fieldCollegeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UserFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userPhoneNumber)
                    .addComponent(fieldPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(UserFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userEmailAddress)
                    .addComponent(fieldEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UserFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldCurrentStreetName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userCurrentStreetName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UserFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldCurrentAptNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userCurrentAptNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UserFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldCurrentCityName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userCurrentCityName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UserFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldCurrentStateName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userCurrentStateName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UserFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldCurrentZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userCurrentZipCode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UserFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldPermanentStreetName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userPermanentStreetName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UserFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldPermanentAptNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userPermanentAptNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UserFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldPermanentCityName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userPermanentCityName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UserFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldPermanentStateName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userPermanentStateName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UserFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldPermanentZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userPermanentZipCode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(save)
                .addGap(27, 27, 27))
        );

        jSplitPane1.setLeftComponent(UserFormPanel);

        ViewPanel.setBackground(new java.awt.Color(204, 255, 204));

        viewNUID.setText("001202400");

        viewFirstName.setText("Hao");

        viewLastName.setText("Liu");

        viewCollegeName.setText("COE");

        viewPhoneNum.setText("8573898812");

        viewEmailAddress.setText("liu.hao5@northeastern.edu");

        viewCurrentStreetName.setText("34 Munroe St");

        viewCurrentAptNumber.setText("Apt 801");

        viewCurrentCityName.setText("Lynn");

        viewCurrentStateName.setText("MA");

        viewCurrentZipCode.setText("01901");

        viewPermanentStreetName.setText("No.528 North Guangxi RD");

        viewPermanentAptNumber.setText("Rm 1607");

        viewPermanentCityName.setText("Shanghai");

        viewPermanentStateName.setText("Shanghai");

        viewPermanentZipCode.setText("200001");

        javax.swing.GroupLayout ViewPanelLayout = new javax.swing.GroupLayout(ViewPanel);
        ViewPanel.setLayout(ViewPanelLayout);
        ViewPanelLayout.setHorizontalGroup(
            ViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewPanelLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(ViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewPermanentZipCode)
                    .addComponent(viewPermanentStateName)
                    .addComponent(viewPermanentCityName)
                    .addComponent(viewPermanentAptNumber)
                    .addComponent(viewPermanentStreetName)
                    .addComponent(viewCurrentZipCode)
                    .addComponent(viewCurrentStateName)
                    .addComponent(viewCurrentCityName)
                    .addComponent(viewCurrentAptNumber)
                    .addComponent(viewCurrentStreetName)
                    .addComponent(viewEmailAddress)
                    .addComponent(viewPhoneNum)
                    .addComponent(viewCollegeName)
                    .addComponent(viewLastName)
                    .addComponent(viewFirstName)
                    .addComponent(viewNUID))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        ViewPanelLayout.setVerticalGroup(
            ViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewPanelLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(viewNUID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(viewFirstName)
                .addGap(12, 12, 12)
                .addComponent(viewLastName)
                .addGap(18, 18, 18)
                .addComponent(viewCollegeName)
                .addGap(18, 18, 18)
                .addComponent(viewPhoneNum)
                .addGap(12, 12, 12)
                .addComponent(viewEmailAddress)
                .addGap(18, 18, 18)
                .addComponent(viewCurrentStreetName)
                .addGap(18, 18, 18)
                .addComponent(viewCurrentAptNumber)
                .addGap(18, 18, 18)
                .addComponent(viewCurrentCityName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(viewCurrentStateName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(viewCurrentZipCode)
                .addGap(18, 18, 18)
                .addComponent(viewPermanentStreetName)
                .addGap(12, 12, 12)
                .addComponent(viewPermanentAptNumber)
                .addGap(18, 18, 18)
                .addComponent(viewPermanentCityName)
                .addGap(18, 18, 18)
                .addComponent(viewPermanentStateName)
                .addGap(18, 18, 18)
                .addComponent(viewPermanentZipCode)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(ViewPanel);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldCurrentStreetNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCurrentStreetNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCurrentStreetNameActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:           
        
        String nUID = fieldNUID.getText();
        String firstName = fieldFirstName.getText();
        String lastName = fieldLastName.getText();
        String collegeName = fieldCollegeName.getText();
        String phoneNumber = fieldPhoneNumber.getText();
        String emailAddress = fieldEmailAddress.getText();
        String currentStreetName = fieldCurrentStreetName.getText();
        String currentAptNumber = fieldCurrentAptNumber.getText();
        String currentCityName = fieldCurrentCityName.getText();
        String currentStateName = fieldCurrentStateName.getText();
        String currentZipCode = fieldCurrentZipCode.getText();
        String permanentStreetName = fieldPermanentStreetName.getText();
        String permanentAptNumber = fieldPermanentAptNumber.getText();
        String permanentCityName = fieldPermanentCityName.getText();
        String permanentStateName = fieldPermanentStateName.getText();
        String permanentZipCode = fieldPermanentZipCode.getText();
        
        this.person.setNUID(nUID);
        this.person.setFirstName(firstName);
        this.person.setLastName(lastName);
        this.person.setCollegeName(collegeName);
        this.contactinfo.setPhoneNum(phoneNumber);
        this.contactinfo.setEmailAddress(emailAddress);
        this.address.setCurrentStreetName(currentStreetName);
        this.address.setCurrentAptNum(currentAptNumber);
        this.address.setCurrentCityName(currentCityName);
        this.address.setCurrentStateName(currentStateName);
        this.address.setCurrentZipCode(currentZipCode);
        this.address.setPermanentStreetName(permanentStreetName);
        this.address.setPermanentAptNum(permanentAptNumber);
        this.address.setPermanentCityName(permanentCityName);
        this.address.setPermanentStateName(permanentStateName);
        this.address.setPermanentZipCode(permanentZipCode);        

        
        JOptionPane.showMessageDialog(null, "SAVED SUCCESSFULLY!");
        
        display();
    }//GEN-LAST:event_saveActionPerformed

    private void fieldNUIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNUIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNUIDActionPerformed

    private void fieldCollegeNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCollegeNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCollegeNameActionPerformed

    private void fieldPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPhoneNumberActionPerformed

    private void fieldEmailAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldEmailAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldEmailAddressActionPerformed

    private void fieldCurrentAptNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCurrentAptNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCurrentAptNumberActionPerformed

    private void fieldCurrentCityNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCurrentCityNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCurrentCityNameActionPerformed

    private void fieldCurrentStateNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCurrentStateNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCurrentStateNameActionPerformed

    private void fieldCurrentZipCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCurrentZipCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCurrentZipCodeActionPerformed

    private void fieldPermanentStreetNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPermanentStreetNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPermanentStreetNameActionPerformed

    private void fieldPermanentZipCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPermanentZipCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPermanentZipCodeActionPerformed

    private void fieldPermanentAptNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPermanentAptNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPermanentAptNumberActionPerformed

    private void fieldPermanentCityNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPermanentCityNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPermanentCityNameActionPerformed

    private void fieldPermanentStateNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPermanentStateNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPermanentStateNameActionPerformed

    
    private void display() {
        
        viewNUID.setText(this.person.getNUID());
        viewFirstName.setText(this.person.getFirstName());
        viewLastName.setText(this.person.getLastName());
        viewCollegeName.setText(this.person.getCollegeName());
        viewPhoneNum.setText(this.contactinfo.getPhoneNum());
        viewEmailAddress.setText(this.contactinfo.getEmailAddress());
        viewCurrentStreetName.setText(this.address.getCurrentStreetName());
        viewCurrentAptNumber.setText(this.address.getCurrentAptNum());
        viewCurrentCityName.setText(this.address.getCurrentCityName());
        viewCurrentStateName.setText(this.address.getCurrentStateName());
        viewCurrentZipCode.setText(this.address.getCurrentZipCode());
        viewPermanentStreetName.setText(this.address.getPermanentStreetName());
        viewPermanentAptNumber.setText(this.address.getPermanentAptNum());
        viewPermanentCityName.setText(this.address.getPermanentCityName());
        viewPermanentStateName.setText(this.address.getPermanentStateName());
        viewPermanentZipCode.setText(this.address.getPermanentZipCode());
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel UserFormPanel;
    private javax.swing.JPanel ViewPanel;
    private javax.swing.JTextField fieldCollegeName;
    private javax.swing.JTextField fieldCurrentAptNumber;
    private javax.swing.JTextField fieldCurrentCityName;
    private javax.swing.JTextField fieldCurrentStateName;
    private javax.swing.JTextField fieldCurrentStreetName;
    private javax.swing.JTextField fieldCurrentZipCode;
    private javax.swing.JTextField fieldEmailAddress;
    private javax.swing.JTextField fieldFirstName;
    private javax.swing.JTextField fieldLastName;
    private javax.swing.JTextField fieldNUID;
    private javax.swing.JTextField fieldPermanentAptNumber;
    private javax.swing.JTextField fieldPermanentCityName;
    private javax.swing.JTextField fieldPermanentStateName;
    private javax.swing.JTextField fieldPermanentStreetName;
    private javax.swing.JTextField fieldPermanentZipCode;
    private javax.swing.JTextField fieldPhoneNumber;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton save;
    private javax.swing.JLabel userCollegeName;
    private javax.swing.JLabel userCurrentAptNumber;
    private javax.swing.JLabel userCurrentCityName;
    private javax.swing.JLabel userCurrentStateName;
    private javax.swing.JLabel userCurrentStreetName;
    private javax.swing.JLabel userCurrentZipCode;
    private javax.swing.JLabel userEmailAddress;
    private javax.swing.JLabel userFirstName;
    private javax.swing.JLabel userLastName;
    private javax.swing.JLabel userNUID;
    private javax.swing.JLabel userPermanentAptNumber;
    private javax.swing.JLabel userPermanentCityName;
    private javax.swing.JLabel userPermanentStateName;
    private javax.swing.JLabel userPermanentStreetName;
    private javax.swing.JLabel userPermanentZipCode;
    private javax.swing.JLabel userPhoneNumber;
    private javax.swing.JLabel viewCollegeName;
    private javax.swing.JLabel viewCurrentAptNumber;
    private javax.swing.JLabel viewCurrentCityName;
    private javax.swing.JLabel viewCurrentStateName;
    private javax.swing.JLabel viewCurrentStreetName;
    private javax.swing.JLabel viewCurrentZipCode;
    private javax.swing.JLabel viewEmailAddress;
    private javax.swing.JLabel viewFirstName;
    private javax.swing.JLabel viewLastName;
    private javax.swing.JLabel viewNUID;
    private javax.swing.JLabel viewPermanentAptNumber;
    private javax.swing.JLabel viewPermanentCityName;
    private javax.swing.JLabel viewPermanentStateName;
    private javax.swing.JLabel viewPermanentStreetName;
    private javax.swing.JLabel viewPermanentZipCode;
    private javax.swing.JLabel viewPhoneNum;
    // End of variables declaration//GEN-END:variables
}
